# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo This is the first step.
    echo This is the second step.
    echo This is the third step.

  displayName: 'Run a multi-line script'

- script: python test.py
  displayName: 'Run a python file'

- script: python test2.py
  displayName: 'Run a python file from a folder'